---
kind: pipeline
type: docker
name: default

steps:
- name: ubuntu 20:10
  image:  ubuntu:groovy
  commands:
  - export TZ=Africa/Nairobi
  - export DEBIAN_FRONTEND=noninteractive && apt-get -y install tzdata
  - apt-get update
  - apt-get -y install sudo git
  - ./run_pkg.sh

- name: debian 11
  image: debian:bullseye
  commands:
  - export TZ=Africa/Nairobi
  - export DEBIAN_FRONTEND=noninteractive && apt-get -y install tzdata
  - apt-get update
  - apt-get -y install sudo git
  - ./run_pkg.sh