---
kind: pipeline
type: docker
name: default

steps:
- name: ubuntu 20:10
  image:  ubuntu:groovy
  commands:
  - apt-get update
  - apt-get -y install sudo
  - export DEBIAN_FRONTEND=noninteractive

  - ./run_pkg.sh

- name: debian 11
  image: debian:bullseye
  commands:
  - apt-get update
  - apt-get -y install sudo
  - export DEBIAN_FRONTEND=noninteractive

  - ./run_pkg.sh