---
kind: pipeline
type: docker
name: default

steps:
- name: Ubuntu Tests
  image:  ubuntu:groovy
  commands:
  - ./pkg/pre.sh
  - ./run_pkg.sh

- name: Debian Tests
  image: debian:testing
  commands:
  - ./pkg/pre.sh
  - ./run_pkg.sh