# Kitty
[[item]]
file="~/.config/kitty/flavours.conf"
template="kitty"
rewrite=true

# Alacritty
[[item]]
file = "~/.config/alacritty/alacritty.yml"
template = "alacritty"
subtemplate = "default-256"


# Kakoune
[[item]]
file = "~/.config/kak/colors/flavours.kak"
template = "kakoune"
rewrite = true
