#!/bin/bash
replace() {
  # Dynamic alias
  # Replacements For standard utilities
  command -v "$2" >/dev/null && alias $1="$2"
}

replace docker podman
replace cat 'bat -p'
replace cat 'batcat -p'
replace ls exa
replace fd fdfind
# replace find fdfind

# Normal aliases
alias reload='. ~/.bashrc' # Reload bashrc
alias c='reload'           # Reload bashrc

alias html2md='pandoc -f html -t markdown'

# Change linux wallpaper

# Reload current kitty terminal
alias kr='kitty @ set-colors ~/.config/kitty/flavours.conf'
# Change Wallpaper, then change base16 theme
# fx() {
#   cd Pictures
#   fzf --preview "flavours generate -n test -a test dark {} ; flavours apply generated; xfconf-query -c xfce4-desktop -p /backdrop/screen0/monitorDP-1/workspace0/last-image -s /home/ian2/Pictures/{}; term-16-test.sh"
# }

# TODO: Convert to function

# Interactive install Package
alias inx='sudo apt install $(/bin/cat $HOME/.local/inx.txt | fzf --preview-window right --preview "apt show {} 2>/dev/null | batcat -p -l yaml --color always")'
alias inx-refresh='apt list 2>/dev/null | cut -f1 -d"/" | grep -v "Listing..." > ~/.local/inx.txt'

alias a2path='echo "export PATH=$PWD:\$PATH" >> ~/.bashrc' # Add current folder to path

alias ping='ping -c 4'      # Ping only 4 times
alias grh='history | grep ' # Grep history

alias myip='dig +short myip.opendns.com @resolver1.opendns.com -4' # get your ip

# Serve current folder on localhost
alias rbsrv='ruby -run -ehttpd . -p '
alias pysrv='python3 -m http.server'
#TODO: Add caddy & miniserve

# Boring Aliases
alias more='less'
alias grep='grep --colour=auto'
alias egrep='egrep --colour=auto'
alias fgrep='fgrep --colour=auto'

alias cp="cp -i"     # Ask for confirmation before overwrites
alias df='df -h'     # Human readable
alias free='free -h' # Human readable
