#!/bin/bash
## Replacements For standard utilities
command -v podman >/dev/null && alias docker="podman" # Safer Containers
command -v bat >/dev/null && alias cat="bat -p"       # cat with syntax highlighting
command -v exa >/dev/null && alias ls='exa'           # Replacement for ls
command -v fdfind >/dev/null && alias fd='fdfind'           # Replacement for ls
alias reload='source ~/.bashrc'     # reload ~/.bashrc
alias c='clear && source ~/.bashrc' # Clear and reload
alias cp="cp -i"                    # Ask for confirmation before overwrites
alias df='df -h'                    # Human Readable
alias free='free -h'                # Human readable

# Theme Switcher
alias fv='flavours list | xargs -n1 | fzf --preview-window up --preview " flavours apply {} 2>/dev/null ; term-16-test.sh;kr "'
# Reload current kitty terminal
alias kr='kitty @ set-colors ~/.config/kitty/flavours.conf'

alias np='nano -w PKGBUILD'
alias more=less

alias grep='grep --colour=auto'
alias egrep='egrep --colour=auto'
alias fgrep='fgrep --colour=auto'

alias a2path='echo "export PATH=$PWD:\$PATH" >> ~/.bashrc'         # Add current folder to path
alias ping='ping -c 4'                                             # Ping only 4 times
#alias gh='history | grep '                                         # Grep history
alias myip='dig +short myip.opendns.com @resolver1.opendns.com -4' # Get Public IP

# youtube-dl

# Saves to ./ (current folder)
alias ydl='youtube-dl -o "./%(title)s.%(ext)s"'

# 1080p Video
# Saves to ~/Videos/Uploader/Title.ext
alias y1080='youtube-dl -f "[height<=1080]"  -o "~/Videos/%(uploader)s/%(title)s.%(ext)s"   --no-playlist   '

# 720p Video
# Save to ~/Videos/Uploader/Title.ext
alias yhd='youtube-dl   -f "[height<=720]"   -o "~/Videos/%(uploader)s/%(title)s.%(ext)s"   --no-playlist    '
# Video Playlist
# Save to ~/Videos/Uploader/Playlist_Title/Video_Title.ext
alias ypl='youtube-dl   -f "[height<=720]"   -o "~/Videos/%(uploader)s/%(playlist)s/%(title)s.%(ext)s"'

# Audio
# Save to ~/Music/Uploader/Title.ext
alias ymp3='youtube-dl  -f "bestaudio"       -o "~/Music/%(uploader)s/%(title)s.%(ext)s"    --no-playlist -x --audio-format mp3               --embed-thumbnail        '

# Audio Playlist
# Save to ~/Videos/Uploader/Title.ext
alias ypl3='youtube-dl  -f "bestaudio"       -o "~/Audio/%(uploader)s/%(playlist)s/%(title)s.%(ext)s"     -x     --audio-format mp3  '

# Serve current folder on localhost
alias rbsrv='ruby -run -ehttpd . -p '
alias pysrv='python3 -m http.server'
