#!/bin/bash
export GEM_HOME="$HOME/gems"
# export NVIMHOME="$HOME/.config/nvim"
# export NVIMRC="$NVIMHOME/init.vim"

# C Compiler & FLags
export CC="clang"
export CFLAGS="-fsanitize=signed-integer-overflow -fsanitize=undefined -ggdb3 -O3 -std=c11 -Wall -Werror -Wextra -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wshadow"
export LDLIBS="-lm"

# fnm (Fast Nodejs Manager)
if command -v fnm &>/dev/null; then
  eval "$(fnm env)"
fi

# Cargo
command -v cargo >/dev/null &&
  source "$HOME/.cargo/env"

# Default Text Editor
command -v nvim >/dev/null &&
  export EDITOR="nvim"
# Kakoune
# command -v kak >/dev/null &&
#   export EDITOR="kak"

# specific to git
# command -v code >/dev/null &&
#   export EDITOR="code --wait --new-window"

# Sdk Manager (java ecosystem)
source "$HOME/.sdkman/bin/sdkman-init.sh"

# Vscode if in vscode terminal
if [[ "$TERM_PROGRAM" == "vscode" ]]; then
  export EDITOR="code"
fi

# Alternative editors
# command -v kak >/dev/null && export EDITOR="kak"
# command -v code >/dev/null && export EDITOR="code --wait --new-window"
# Default Prompt
PS1="\[\e[32m\]\u\[\e[m\]\[\e[32m\]@\[\e[m\]\[\e[32m\]\h\[\e[m\] \[\e[36m\]\w\[\e[m\] \n; "

# zoxide
command -v zoxide &>/dev/null &&
  eval "$(zoxide init bash)"
# prevent Ctrl-S from pausing the terminal
stty -ixon

# Starship Prompt
command -v starship &>/dev/null &&
  eval "$(starship init bash)"
