#!/bin/bash
# ex - archive extractor ##
# usage: ex <file>
ex() {
  if [ -f "$1" ]; then
    case "$1" in
    *.tar.bz2) tar xjf "$1" ;;
    *.tar.gz) tar xzf "$1" ;;
    *.bz2) bunzip2 "$1" ;;
    *.rar) unrar x "$1" ;;
    *.gz) gunzip "$1" ;;
    *.tar) tar xf "$1" ;;
    *.tbz2) tar xjf "$1" ;;
    *.tgz) tar xzf "$1" ;;
    *.zip) unzip "$1" ;;
    *.Z) uncompress "$1" ;;
    *.7z) 7z x "$1" ;;
    *) echo "'$1' cannot be extracted via ex()" ;;
    esac
  else
    echo "'$1' is not a valid file"
  fi
}

kitty_apply() {
  flavours apply "$1"
  kitty @ set-colors ~/.config/kitty/flavours.conf
}

# Install Programs with fzf
# inx() {
#   # Update List of programs
#   _update_list() {
#     apt list 2>/dev/null |
#       cut -f1 -d"/" |
#       grep -v "Listing..." \
#         >~/.local/inx.txt
#   }
#   # Preview Command
#   _preview_cmd() {
#     apt show {} 2>/dev/null | batcat -p -l yaml --color always
#   }
#   listfile="$HOME/.local/apt-list.txt"
#   cat $listfile | fzf --preview-window right --preview _preview_cmd
#   sudo apt install
# }
# Theme Switcher
fv() {
  flavours list |
    xargs -n1 |
    fzf --preview "flavours apply {} 2>/dev/null ;term-16-test.sh"
}

kv() (

  flavours list |
    xargs -n1 |
    fzf --preview "flavours apply {} && kitty @ set-colors ~/.config/kitty/flavours.conf"
)
